# Generated by Django 4.2.3 on 2023-07-20 18:42

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggyWaggy', '0003_remove_thingie_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingie',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
