# Generated by Django 4.2.3 on 2023-07-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggyWaggy', '0004_thingie_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thingie',
            name='timeline',
        ),
    ]
