# Generated by Django 4.2.3 on 2023-07-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggyWaggy', '0005_remove_thingie_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingie',
            name='creator',
            field=models.CharField(default='Frankenstein', max_length=255),
        ),
        migrations.AddField(
            model_name='thingie',
            name='description',
            field=models.CharField(default='new', max_length=255),
        ),
        migrations.AlterField(
            model_name='thingie',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
