# Generated by Django 4.2.3 on 2023-07-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggyWaggy', '0007_alter_thingie_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingie',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
